py_test(
    name = "spectral_test",
    srcs = ["spectral_test.py"],
    deps = ["spectral"],
)

py_library(
    name = "spectral",
    srcs = ["spectral.py"],
    deps = [],
)

py_test(
    name = "layers_test",
    srcs = ["layers_test.py"],
    deps = ["layers"],
)

py_library(
    name = "layers",
    srcs = ["layers.py"],
    deps = [],
)
